/*
 * Finvenkisto
 *
 * Copyright (C) 2015 Neil Roberts
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "config.h"

#include <math.h>

#include "fv-person.h"

const struct fv_person_npc
fv_person_npcs[FV_PERSON_N_NPCS] = {
        /* People outside the center doing la bamba */
        { 4.712389, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 4.319690, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 3.926991, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO3,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 3.534292, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 3.141592, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 2.748893, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 2.356194, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 1.963495, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO3,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 1.570796, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 1.178097, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 0.785398, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 0.392699, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 0.000000, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 5.890487, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO3,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 5.497787, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },
        { 5.105088, 8.75, 39.25,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_CIRCLE,
          .circle = { .radius = 4.0 } },

        /* People milling around in the center of La Bamba */
        { 5.301438, 10.681195, 40.0947,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1687 } },
        { 3.632467, 8.175107, 40.4851,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 2404 } },
        { 6.062292, 7.429351, 37.5790,
          FV_PERSON_TYPE_BAMBISTO3,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 2718 } },
        { 1.570796, 6.010022, 39.4742,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1003 } },
        { 5.546875, 9.493217, 37.0458,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1880 } },
        { 5.031457, 9.684329, 38.6340,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1011 } },
        { 5.417243, 9.124920, 41.4923,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1608 } },
        { 1.827340, 6.418345, 40.7912,
          FV_PERSON_TYPE_BAMBISTO1,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 8.75, .center_y = 39.25,
                      .radius = 3.0,
                      .retarget_time = 1968 } },
        { 2 * M_PI - 0.625 * M_PI, 32.5, 38.75,
          FV_PERSON_TYPE_GUFUJESTRO,
          FV_PERSON_MOTION_STATIC },
        { M_PI, 33.5, 14.5,
          FV_PERSON_TYPE_TOILET_GUY,
          FV_PERSON_MOTION_STATIC },
        { 0.0, 31, 28,
          FV_PERSON_TYPE_PYJAMAS,
          FV_PERSON_MOTION_RANDOM,
          .random = { .center_x = 31, .center_y = 28,
                      .radius = 6.0,
                      .retarget_time = 1050 } },
        { 1.3 * M_PI, 28, 16,
          FV_PERSON_TYPE_PYJAMAS,
          FV_PERSON_MOTION_STATIC },
        { 1.6 * M_PI, 4, 26,
          FV_PERSON_TYPE_GUFUJESTRO,
          FV_PERSON_MOTION_STATIC },
        { 1.6 * M_PI, 36, 37.5,
          FV_PERSON_TYPE_BAMBISTO2,
          FV_PERSON_MOTION_STATIC },
};
