FV_VK_FUNC(vkCreateDevice)
FV_VK_FUNC(vkDestroyInstance)
FV_VK_FUNC(vkDestroySurfaceKHR)
FV_VK_FUNC(vkEnumerateDeviceExtensionProperties)
FV_VK_FUNC(vkEnumeratePhysicalDevices)
FV_VK_FUNC(vkFlushMappedMemoryRanges)
FV_VK_FUNC(vkGetDeviceProcAddr)
FV_VK_FUNC(vkGetPhysicalDeviceFeatures)
FV_VK_FUNC(vkGetPhysicalDeviceFormatProperties)
FV_VK_FUNC(vkGetPhysicalDeviceMemoryProperties)
FV_VK_FUNC(vkGetPhysicalDeviceProperties)
FV_VK_FUNC(vkGetPhysicalDeviceQueueFamilyProperties)
FV_VK_FUNC(vkGetPhysicalDeviceSurfaceCapabilitiesKHR)
FV_VK_FUNC(vkGetPhysicalDeviceSurfaceFormatsKHR)
FV_VK_FUNC(vkGetPhysicalDeviceSurfacePresentModesKHR)
FV_VK_FUNC(vkGetPhysicalDeviceSurfaceSupportKHR)

#ifdef WIN32
FV_VK_FUNC(vkCreateWin32SurfaceKHR)
#else
FV_VK_FUNC(vkCreateXlibSurfaceKHR)
FV_VK_FUNC(vkCreateWaylandSurfaceKHR)
#endif
